language: R
cache:
  packages: true
  directories:
  - _book

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
	- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
